### ISSUE TITLE
Consider switching to OpenBLAS

### ISSUE THREAD

**Issue by cmr** [stainless-steel/libblas-sys#1]
I've written a complete BLAS/LAPACK binding here: https://github.com/cmr/libblas-sys

By default it will build and link to OpenBLAS, which is one of the fastest BLAS providers, and the only threadsafe parallel one. The netlib BLAS included here is extremely slow. I'm more than happy to maintain this etc, with a `cargo owner --add cmr` and contrib to this repo. Otherwise, I'll just publish that crate as `libopenblas-sys`.

**Comment by IvanUkhov** [comment]
What you have done is really awesome! But don’t you think that `libopenblas-sys` is a more appropriate name for your bindings? Because you’re building `libopenblas`, not `libblas`. I’ll be happy to switch to your library for my personal projects if the speedup is as dramatic as you say. Thanks.

Regards,
Ivan

**Comment by cmr** [comment]
Thing is, the netlib BLAS isn't "the BLAS", and my goal with that `libblas-sys` is that it *could* build any BLAS, but OpenBLAS is the fastest threadsafe one I know of, so that's the only one I implemented. Feature gates can let you pick which BLAS you want.

**Comment by IvanUkhov** [comment]
I see. But then OpenBLAS isn’t pure BLAS either since it includes LAPACK. Regarding thread-safety, [as far as I know][1], Netlib’s version doesn’t have this problem since v3.3.0.

[1]: http://www.netlib.org/lapack/lapack-3.3.0.html

**Comment by IvanUkhov** [comment]
@cmr, how about splitting your bindings into BLAS and LAPACK, as I did, and then publishing them as two separate crates? We could maintain both libraries together.

**Comment by cmr** [comment]
Sounds like a good plan.

**Comment by cmr** [comment]
Idea: two core crates, `libblas-sys` and `liblapack-sys` that don't build or link to any library, but instead provide features that link to a "BLAS provider" and "LAPACK provider", where those are building/linking to a real implementation. Then these providers would be a bunch of crates, one for OpenBLAS (which is both), two for netlib, one for MKL, ACML, etc.

**Comment by IvanUkhov** [comment]
@cmr, I absolutely support the idea. Right now I’m compiling in both libraries, and there’s an overlap there since LAPACK pulls BLAS (without mangling CMakeLists), which results in a non-optimal compilation time. With a joint BLAS/LAPACK provide, the problem will vanish.

**Comment by IvanUkhov** [comment]
@cmr, I’ve added you to the authors on crates.io for both `libblas-sys` and `liblapack-sys`. You should be able to publish when the issue with `openblas-blas-provider` is resolved.

**Comment by cmr** [comment]
Thanks!
