### ISSUE TITLE
Short names

### ISSUE THREAD

**Issue by IvanUkhov** [stainless-steel/libblas-sys#3]
I have noticed that `liblapack-sys` provides short names like `dsyev_`, but `libblas-sys` does not, which is a bit inconsistent. Do you think `dgemv_` and such should be included in the bindings? Thanks.

/cc @cmr

**Comment by IvanUkhov** [comment]
I guess the idea is to match exactly the corresponding C headers, [cblas.h][1] and [lapacke.h][2]. Then everything makes sense and should be kept as it is.

[1]: https://raw.githubusercontent.com/copies/lapack/master/CBLAS/include/cblas.h

[2]: https://raw.githubusercontent.com/copies/lapack/master/LAPACKE/include/lapacke.h

**Comment by cmr** [comment]
Right, I bound against CBLAS instead of using the Fortran ABI directly. I could go either way to be honest.
